title: "My Dark Blog"
description: "A Jekyll blog with permanent dark mode"
baseurl: ""
theme: minima

minima:
  skin: classic
  show_excerpts: true
  date_format: "%b %-d, %Y"

# Optional: GitHub username for footer link
github_username: apaleblueman

# Pagination (optional)
paginate: 5        # number of posts per page
paginate_path: "/page:num/"   # optional


